FROM ekidd/rust-musl-builder:latest as builder

WORKDIR /home/rust/src
COPY . .

# Build statically linked binary
RUN cargo build --release --target x86_64-unknown-linux-musl

# Create the runtime directory
FROM scratch
COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/chrome-lambda-rust /bootstrap
ENTRYPOINT ["/bootstrap"] 